version: "3.8"

services:
  webserver:
    container_name: webserver
    build: "./webserver"
    ports:
      - 3000:3000
    depends_on: 
      - apollo
  apollo:
    container_name: apollo
    build: "./apollo"
    environment: 
      DB_USERNAME: root
      DB_PASSWORD: rootpassword
      DB_NAME: USER
      DB_PORT: 27017
    ports:
      - 4000:4000
    depends_on:
      - database
  database:
    container_name: database
    image: mongo:latest
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: rootpassword
    ports:
      - 27017:27017
    volumes:
      - type: volume
        source: mongodb-data
        target: /data/db
volumes:
  mongodb-data:
